---
title: "group project excel join"
author: "Aryss Hearne"
date: "2/26/2021"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
eukaryotes<-readr::read_csv("data/eukaryotes.csv")
prokaryotes<-readr::read_csv("data/prokaryotes.csv")
```

```{r}
#names(eukaryotes)
#names(prokaryotes)
```


```{r}
organism_data<-full_join(eukaryotes,prokaryotes)
organism_data
```

```{r}
organism_data2<-
  organism_data%>%
  separate(`Organism Name`, into = c("genus", "species"),sep=" ")%>%
  separate(`Organism Groups`, into = c("domain","kingdom","subgroup"),sep=";")
organism_data2
```

```{r}
organism_data3<-organism_data2%>%
  select(domain, kingdom, subgroup, genus, species,`Size(Mb)`, 'GC%', CDS, Genes)%>%
  rename(size_mb='Size(Mb)', perc_gc="GC%", protein_coding_genes="CDS", genes="Genes")
organism_data3
```

```{r}
#organism_data3%>%
  #filter(kingdom=="Proteobacteria") #just making sure the prokaryotes made it in
```

